name: Tạo thống kê GitHub

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Run using Python 3.13 for consistency and aiohttp
    - name: Cài đặt Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        architecture: 'x64'
        cache: 'pip'

    # Install dependencies with `pip`
    - name: Cài đặt dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate all statistics images
    - name: Tạo ảnh thống kê
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: ${{ secrets.EXCLUDE_FORKED_REPOS }}

    - name: Chuẩn bị số liệu thống kê để triển khai
      run: |
          mkdir -p dist/assets/stats
          # copy outputs from common places (adjust if your generate_images.py writes elsewhere)
          if [ -d generated ]; then
            cp -r generated/* dist/assets/stats/ || true
          else
            cp -r *.svg dist/assets/stats/ || true
          fi

    - name: Upload stats artifact
      uses: actions/upload-artifact@v4
      with:
        name: stats-artifact
        path: dist/assets/stats

  snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/assets/snake/github-contribution-grid-snake.svg
            dist/assets/snake/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload snake artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-artifact
          path: dist/assets/snake

  deploy:
    runs-on: ubuntu-latest
    needs: [stats, snake]

    steps:
      - name: Tải xuống thống kê Stats
        uses: actions/download-artifact@v4
        with:
          name: stats-artifact
          path: dist/assets/stats

      - name: Tải xuống thống kê Snake
        uses: actions/download-artifact@v4
        with:
          name: snake-artifact
          path: dist/assets/snake

      - name: Triển khai tới gh-output (đẩy một lần, ghi đè lên các tệp)
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: gh-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}